--- #YAML:1.0
name:                HTML-Dojo
version:             0.0401.0
abstract:            Provides the Dojo JavaScript / AJAX distribution 0.4.1 files.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Carl Franks <cfranks@cpan.org>
